### PR TITLE
ADD code coverage report

### LINKED ISSUE #30: Implement code coverage report
Looks like the tool Kakapo.js uses is also available for us https://github.com/codecov/example-objc

### PR DESCRIPTION
**Pull request by MP0w**
Closes #30

### CODE REVIEW

**Comment by MP0w** [comment]
@joanromano take a look, I switched to Fastlane now, not sure if it is perfect we may also want a build matrix

**Comment by MP0w** [comment]
I will squash the commits when merging

**Comment by MP0w** [comment]
@joanromano apparently `dispatch_get_specific` is not covered, I will check if it's still needed with the current implementation but probably no.

**Comment by joanromano** [comment]
👍

**Pull request merged**
