### PR TITLE
Restore Swift 2.2 support

### PR DESCRIPTION
**Pull request by amarcadet**
Related to https://github.com/devlucky/Kakapo/issues/133

### CODE REVIEW

**Comment by joanromano** [comment]
Please update Readme accordingly:

```
Swift 2.2 and 2.3 compatible (from version 1.0.0, branch feature/legacy-swift)
```

instead of:

```
Swift 2.3 compatible (from version 1.0.0, branch feature/legacy-swift)
Swift 2.2 compatible (versions 0.x.y)
```

**Comment by joanromano** [comment]
Please update the Changelog

**Review by MP0w — APPROVED** [review]
After README seems good to merge. 
Let's keep the related issue open until I update ci and we release a version in CP that reintroduce swift 2.2 support.
Ty!
PS: If you only update README use "[ci skip]" in the commit message because Travis is really slow these days

**Comment by amarcadet** [comment]
No problem for updating README and Changelog, however what version number would you use?
Per semver, I don't know if it's more a 1.1.1 or 1.2.0.

Thanks for the ci tip!

**Comment by MP0w** [comment]
I think 1.2.0 maybe but don't worry about Cocoapods we will take care of release

**Comment by MP0w** [comment]
Ah if it's for the changelog just put it under HEAD

**Pull request merged**
