### PR TITLE
Use Nimble’s throw assertion matcher #139 #trivial

### LINKED ISSUE #139: Test some assertions with Quick
We finally have this https://github.com/Quick/Nimble/pull/248#event-826944480 so we can test some assertions in Store for instance

### PR DESCRIPTION
**Pull request by MP0w**
Closes #139 

Also:
removed the previous CustomAsserion.swift implementation
Fixed some new swiftlint warnings

### CODE REVIEW

**Comment by MP0w** [comment]
Apparently it only works on 64 bits... either we exclude it from the job that uses iPhone 5 or we roll back. I would still keep a job on 32 bit simulator

**Review by joanromano — APPROVED** [review]

**Comment by joanromano** [comment]
@MP0w strange, I was able to run them on a different project for 32 bit as well

**Comment by MP0w** [comment]
@joanromano maybe is the ci?

**Comment by MP0w** [comment]
@joanromano doesn't work on simulators < 5s, it's also documented

**Pull request merged**
